spring:
  aws:
    dynamodb:
      endpoint: ${DYNAMODB_ENDPOINT:http://localhost:4566}
      region: ${AWS_REGION:us-east-1}
      access-key: ${AWS_ACCESS_KEY_ID:fakeAccessKey}
      secret-key: ${AWS_SECRET_ACCESS_KEY:fakeSecretKey}
      table-name: ${DYNAMO_USERS_TABLE:tb_users}

app:
  version: 00.04.00